name: CI

on:
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rvm: [2.0.0,2.1.0,2.2.0,2.5.8,jruby-19mode]
    steps:
    - uses: zendesk/checkout@v2
    - name: Set up Ruby
      uses: zendesk/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.rvm }}
    - name: Test ${{ matrix.rvm }}
      run: bundle exec rspec spec
